#%RAML 1.0 Trait
headers:
  transactionId:
    description: "this input will help for tracking status of transaction"
    type: string
    required: true
    example: "hdsfhjdh-jxbv859-sjdf7643-3746bbd"